version: '3'

services:
  scimgateway:
    build: ./scimgateway
    ports:
      - "8880:8880"
    restart: always
    environment:
      loki-new-connector-5_BEARER_0_TOKEN: 1234
      loki-new-connector-5_OAUTH2_0_CLIENT_ID: null
      loki-new-connector-5_OAUTH2_0_CLIENT_SECRET: null
      loki-new-connector-5_OAUTH2_1_CLIENT_ID: a
      loki-new-connector-5_OAUTH2_1_CLIENT_SECRET: a

    volumes:
      - data:/home/node/app/data
   
  forms:
    depends_on:
      - scimgateway
    build: ./forms
    ports:
      - "8000:80"
    restart: always
  
     

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/luciana/Documents/qscim-files/finished/data