version: '3'

services:
  scimgateway:
    build: ./scimgateway
    ports:
      - "8881:8881"
    restart: always
    environment:
      loki-new-connector---test_BASIC_0_USERNAME: a
      loki-new-connector---test_BASIC_0_PASSWORD: a

    volumes:
      - data:/home/node/app/data
   
  forms:
    depends_on:
      - scimgateway
    build: ./forms
    ports:
      - "8000:80"
    restart: always
  
     

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/luciana/Documents/qscim-files/finished/data