version: '3'

services:
  scimgateway:
    build: ./scimgateway
    ports:
      - "8880:8880"
    restart: always
    environment:
      loki-new-connector_BASIC_0_USERNAME: a
      loki-new-connector_BASIC_0_PASSWORD: a
      loki-new-connector_BEARER_1_TOKEN: aaaaaaaaaaaaaaaaaaaaaaaaaaaa
      loki-new-connector_OAUTH2_1_CLIENT_ID: null
      loki-new-connector_OAUTH2_1_CLIENT_SECRET: null

    volumes:
      - data:/home/node/app/data
   
  forms:
    depends_on:
      - scimgateway
    build: ./forms
    ports:
      - "8000:80"
    restart: always
  
     

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/luciana/Documents/qscim-files/finished/data